apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  data:
    - secretKey: NTFY_URL
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: ntfy.auth
        property: url
    - secretKey: NTFY_BAUTH_USER
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: ntfy.auth
        property: username
    - secretKey: NTFY_BAUTH_PASS
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: ntfy.auth
        property: password
    - secretKey: BAUTH_PASS
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: ntfy-relay.auth
        property: password
